# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-17 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=120)),
                ('date', models.DateField()),
                ('text', models.TextField()),
                ('fb_graph_api_id', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='articleorcomment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='articleorcomment',
            name='parent',
        ),
        migrations.DeleteModel(
            name='ArticleOrComment',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
